services:
  postgres:
    image: postgres:15-alpine
    container_name: bidding-system-db
    environment:
      POSTGRES_DB: bidding_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bidding-network

  backend:
    build: .
    container_name: bidding-system-backend
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_NAME: bidding_system
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    networks:
      - bidding-network
volumes:
  postgres_data:

networks:
  bidding-network:
    driver: bridge 